# Generated by Django 4.1.5 on 2023-02-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCRVS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='name',
            field=models.CharField(default='hera', max_length=250, unique=True),
        ),
    ]
