# Generated by Django 4.1.5 on 2023-02-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCRVS', '0004_alter_citizen_birth_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
